### ISSUE TITLE
How to Read Objects Values without Access Key?

### ISSUE THREAD

**Issue by MSTIGM** [ayumax/EasyJsonParser#2]
Hi,
Thanks a lot for your very useful and AWESOME plugin :-) ...
I have a question:
How can I read an integer array without access key?
I mean something like this:
{
   "obj": [ 0, 1, 2, 3, 4, 5, ...]
}
When I use "Read Objects" node (with For Each Loop) with "Access Key = obj", It only shows a lot of 0 !
Thank you so much for your attention :-) ...
Kind Regards.

**Comment by ayumax** [comment]
Excuse me. I thought about it, but did not provide a method to get all arrays other than Object (intger etc.).

'ReadObjects' considers the child element as an Object, so you can't get the value after that.

Although it is a rather unnatural implementation, you can get it by creating'Access String' after acquiring the number of elements with ReadObjects as shown below.

In the future, we will consider ways to obtain it more naturally.

![image](https://user-images.githubusercontent.com/8191970/86136588-3d03cf80-bb27-11ea-801d-ae1f59a2e471.png)

**Comment by MSTIGM** [comment]
Dear Ayuma,

THANKS A MILLION for your help :-) ...
It worked PERFECT for me :-) !!! You're a genius :-) ...
I'm always looking forward for your updates :-) ...

Wish you the BEST :-) ...
Take Care and Stay Safe...

Kind Regards,
Stig
